/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/appbar/Auth.vue')['default']
    CreateLoadingView: typeof import('./src/components/common/CreateLoadingView.vue')['default']
    FloatingButton: typeof import('./src/components/common/FloatingButton.vue')['default']
    LoadingView: typeof import('./src/components/common/LoadingView.vue')['default']
    Main: typeof import('./src/components/main/Main.vue')['default']
    NotAuth: typeof import('./src/components/appbar/NotAuth.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongCard: typeof import('./src/components/song/SongCard.vue')['default']
    SongDetail: typeof import('./src/components/song/SongDetail.vue')['default']
    SongList: typeof import('./src/components/song/SongList.vue')['default']
    StoryBook: typeof import('./src/components/song/StoryBook.vue')['default']
    StoryCreateBook: typeof import('./src/components/story/StoryCreateBook.vue')['default']
    StoryKeyword: typeof import('./src/components/song/StoryKeyword.vue')['default']
  }
}
